language: cpp
sudo: false   # Use the new container infrastructure

matrix:
  include:
    - os: linux
      env:
        - CXX_COMPILER=g++-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ["g++-5", "doxygen", "cmake"]
    - os: linux
      env:
        - COMPILER=clang++-3.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ["clang-3.8", "cmake"]
    - os: osx
      osx_image: xcode7
      env:
        - COMPILER=clang++
        - COMPILER=clang++

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake lcov python
    fi

  - pip install --user codecov

  - sh ${COMPILER} --version || true

before_script:
  - rm -rf build/
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_CXX_FLAGS="-coverage -fprofile-arcs -ftest-coverage" -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cmake --build .
  - ctest

after_success:
  - codecov